In [87]:
import pandas as pd
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection

from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
linear_model.LinearRegression()
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [122]:
dataset = pd.read_csv('data/bat_shelf.csv')

In [123]:
#clean up dataset
dataset[dataset['Cap'] > 1] = 1
dataset = dataset[dataset.Cap != 0]
dataset

Unnamed: 0    PLN    SOC  TEMP Time  Discharge Capacity  Elap_time  \
0             0    3.0    0.0  50.0   3W            1.568073        0.0   
1             1    4.0    0.0  50.0   3W            1.557777        0.0   
2             2    5.0    0.0  50.0   3W            1.571983        0.0   
3             3    6.0    0.0  50.0   3W            1.563704        0.0   
4             4   15.0  100.0  50.0   3W            1.576211        0.0   
5             5   16.0  100.0  50.0   3W            1.556422        0.0   
6             6   17.0  100.0  50.0   3W            1.573830        0.0   
7             7   18.0  100.0  50.0   3W            1.559845        0.0   
8             8   27.0   50.0  50.0   3W            1.557496        0.0   
9             9   28.0   50.0  50.0   3W            1.545928        0.0   
10           10   29.0   50.0  50.0   3W            1.557193        0.0   
11           11   30.0   50.0  50.0   3W            1.568564        0.0   
12           12   51.0   50.0  25.0   3W            1.575481        0.0   
13           13   52.0   50.0  25.0   3W            1.548830        0.0   
14           14   53.0   50.0  25.0   3W            1.554214        0.0   
15           15   54.0   50.0  25.0   3W            1.564188        0.0   
16           16   67.0    0.0  25.0   3W            1.563985        0.0   
17           17   68.0    0.0  25.0   3W            1.548103        0.0   
18           18   69.0    0.0  25.0   3W            1.544983        0.0   
19           19   70.0    0.0  25.0   3W            1.554105        0.0   
20           20   71.0  100.0  25.0   3W            1.569579        0.0   
21           21   72.0  100.0  25.0   3W            1.551388        0.0   
22           22   73.0  100.0  25.0   3W            1.552581        0.0   
23           23   74.0  100.0  25.0   3W            1.542345        0.0   
24           24   83.0   50.0  -5.0   3W            1.564973        0.0   
25           25   84.0   50.0  -5.0   3W            1.561187        0.0   
26           26   85.0   50.0  -5.0   3W            1.561907        0.0   
27           27   86.0   50.0  -5.0   3W            1.569983        0.0   
28           28   95.0  100.0  -5.0   3W            1.550215        0.0   
29           29   96.0  100.0  -5.0   3W            1.566354        0.0   
..          ...    ...    ...   ...  ...                 ...        ...   
525         525  121.0   50.0 -40.0   3W            1.583488       84.0   
526         526  122.0   50.0 -40.0   3W            1.563656       84.0   
527         527  127.0  100.0 -40.0   3W            1.546278       84.0   
528         528  128.0  100.0 -40.0   3W            1.568275       84.0   
529         529  129.0  100.0 -40.0   3W            1.540256       84.0   
530         530  130.0  100.0 -40.0   3W            1.550761       84.0   
531         531  119.0   50.0 -40.0   3W            1.551868      105.0   
532         532  120.0   50.0 -40.0   3W            1.558346      105.0   
533         533  121.0   50.0 -40.0   3W            1.583488      105.0   
534         534  122.0   50.0 -40.0   3W            1.563656      105.0   
535         535  127.0  100.0 -40.0   3W            1.546278      105.0   
536         536  128.0  100.0 -40.0   3W            1.568275      105.0   
537         537  129.0  100.0 -40.0   3W            1.540256      105.0   
538         538  130.0  100.0 -40.0   3W            1.550761      105.0   
539         539  119.0   50.0 -40.0   3W            1.551868      126.0   
540         540  120.0   50.0 -40.0   3W            1.558346      126.0   
541         541  121.0   50.0 -40.0   3W            1.583488      126.0   
542         542  122.0   50.0 -40.0   3W            1.563656      126.0   
543         543  127.0  100.0 -40.0   3W            1.546278      126.0   
544         544  128.0  100.0 -40.0   3W            1.568275      126.0   
545         545  129.0  100.0 -40.0   3W            1.540256      126.0   
546         546  130.0  100.0 

In [124]:
# Split-out validation dataset
array = dataset.values
X = array[:,[2,3,6]]
Y = array[:,7]
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)


In [125]:
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_validation)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(Y_validation, Y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(Y_validation, Y_pred))


Coefficients: 
 [-0.0001476  -0.000235   -0.00019712]
Mean squared error: 0.00
Variance score: 0.34


In [126]:
#Try with adding polynomial features
array = dataset.values
X = array[:,[2,3,6]]
Y = array[:,7]

poly = PolynomialFeatures(2)
X2 = poly.fit_transform(X)

validation_size = 0.20
seed = 7
X2_train, X2_validation, Y_train, Y_validation = model_selection.train_test_split(X2, Y, test_size=validation_size, random_state=seed)

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X2_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X2_validation)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(Y_validation, Y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(Y_validation, Y_pred))

Coefficients: 
 [  0.00000000e+00   3.99000652e-04   8.09465504e-04  -2.54979706e-04
  -1.06648562e-06  -8.67078503e-06  -4.45118349e-06  -1.39564010e-05
  -6.57982192e-06   2.42634909e-06]
Mean squared error: 0.00
Variance score: 0.67


In [224]:
#predict arb value
X3 = np.array([0, 50, 60])


poly = PolynomialFeatures(2)
X4 = poly.fit_transform(X3.reshape(1,-1))
a = regr.predict(X4)

In [225]:
a

array([ 0.97781006])

In [223]:
X3 = np.array([0, 50, 60])
X3.reshape(1,-1)

array([[ 0, 50, 60]])