In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import bat_model
%matplotlib inline

In [ ]:
df = pd.read_csv('../data/SM_forecast_2016.csv')
df['temperature'] = (df['temperature'] - 32)*(5/9)
DailyTemp = []
for ii in range(365):
    DailyTemp.append(df.loc[ii*24:ii*24+24,'temperature'].mean(axis=0))

In [ ]:
df = pd.read_csv('../data/Salem_forecast_2016.csv')
df['temperature'] = (df['temperature'] - 32)*(5/9)
DailyTemp2 = []
for ii in range(365):
    DailyTemp2.append(df.loc[ii*24:ii*24+24,'temperature'].mean(axis=0))

In [1]:
df = pd.read_csv('../data/Salem_forecast_2016.csv')
df['temperature'] = (df['temperature'] - 32)*(5/9)
DailyTemp3 = []
for ii in range(365):
    DailyTemp3.append(df.loc[ii*24:ii*24+24,'temperature'].mean(axis=0))

NameError: name 'pd' is not defined

In [ ]:
Cap = []
Cap.append(1)
soc = 50
cycles = 0
soc_low = 0
soc_high = 80
rate = 1
for ii in range(365):    
    Cap.append(BatFNs.bat_day(soc,DailyTemp[ii],cycles,soc_low,soc_high,rate)*Cap[ii])
    
Cap2 = []
Cap2.append(1)
soc = 50
cycles = 1
soc_low = 0
soc_high = 80
rate = 1
for ii in range(365):    
    Cap2.append(BatFNs.bat_day(soc,DailyTemp[ii],cycles,soc_low,soc_high,rate)*Cap2[ii])
    
Cap3 = []
Cap3.append(1)
soc = 50
cycles = 2
soc_low = 0
soc_high = 80
rate = 1
for ii in range(365):    
    Cap3.append(BatFNs.bat_day(soc,DailyTemp[ii],cycles,soc_low,soc_high,rate)*Cap3[ii])
    
plt.style.use('seaborn')
plt.plot(range(366),Cap,range(366),Cap2,range(366),Cap3)
plt.xlabel('Day of Year', fontsize=18)
plt.ylabel('Capacity Fade',fontsize=18)
plt.title('Operating Battery Santa Maria 2016',fontsize=18)
plt.legend(('0 cycle/day','1 cycle/day','2 cycle/day'),fontsize=14)

In [ ]:
Cap = []
Cap.append(1)
soc = 40
cycles = 1
soc_low = 20
soc_high = 60
rate = 1
for ii in range(365):    
    Cap.append(BatFNs.bat_day(soc,DailyTemp[ii],cycles,soc_low,soc_high,rate)*Cap[ii])
    
Cap2 = []
Cap2.append(1)
soc = 60
cycles = 1
soc_low = 40
soc_high = 80
rate = 1
for ii in range(365):    
    Cap2.append(BatFNs.bat_day(soc,DailyTemp[ii],cycles,soc_low,soc_high,rate)*Cap2[ii])
    
Cap3 = []
Cap3.append(1)
soc = 80
cycles = 1
soc_low = 60
soc_high = 100
rate = 1
for ii in range(365):    
    Cap3.append(BatFNs.bat_day(soc,DailyTemp[ii],cycles,soc_low,soc_high,rate)*Cap3[ii])
    
plt.style.use('seaborn')
plt.plot(range(366),Cap,range(366),Cap2,range(366),Cap3)
plt.xlabel('Day of Year', fontsize=18)
plt.ylabel('Capacity Fade',fontsize=18)
plt.title('Operating Battery Santa Maria 2016',fontsize=18)
plt.legend(('20% <-> 60%','40% <-> 80%','60% <-> 100%'),fontsize=14)

In [ ]:
Cap = []
Cap.append(1)
soc = 100
cycles = 0
soc_low = 0
soc_high = 100
rate = 1
for ii in range(365):    
    Cap.append(BatFNs.bat_day(soc,DailyTemp[ii],cycles,soc_low,soc_high,rate)*Cap[ii])
    
Cap2 = []
Cap2.append(1)
soc = 100
cycles = 0
soc_low = 0
soc_high = 100
rate = 1
for ii in range(365):    
    Cap2.append(BatFNs.bat_day(soc,DailyTemp2[ii],cycles,soc_low,soc_high,rate)*Cap2[ii])
    
Cap3 = []
Cap3.append(1)
soc = 100
cycles = 0
soc_low = 0
soc_high = 100
rate = 1
for ii in range(365):    
    Cap3.append(BatFNs.bat_day(soc,DailyTemp3[ii],cycles,soc_low,soc_high,rate)*Cap3[ii])
    
plt.style.use('seaborn')
plt.plot(range(366),Cap,range(366),Cap2,range(366),Cap3)
plt.xlabel('Day of Year', fontsize=18)
plt.ylabel('Capacity Fade',fontsize=18)
plt.title('Battery Storage (no cycles)',fontsize=18)
plt.legend(('Santa Maria, CA','Salem, OR','Fairbanks, AK'),fontsize=14)

In [ ]:
Cap = []
Cap.append(1)
Shelf = []
Shelf.append(1)
soc = 50
cycle = 0
cycles = 1
soc_low = 0
soc_high = 80
rate = 1
for ii in range(365):
    cycle = cycle + cycles
    (DegCycle, DegStore) = BatFNs.bat_day2(soc,DailyTemp[ii],cycle,soc_low,soc_high,rate)
    Shelf.append(DegStore*Shelf[ii])
    Cap.append(DegStore*Shelf[ii]*DegCycle)

In [ ]:
DailyTemp[ii]

In [ ]:
plt.style.use('seaborn')
plt.plot(Cap)

In [ ]:
df.loc[ii*24:ii*24+24,'temperature'].mean(axis=0)

In [2]:
bat_model.bat_price_per_hour(200,18,22,300,200,100)

array([[ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.00130673],
       [ 0.01435766],
       [ 0.01435766],
       [ 0.01435766],
       [ 0.01435766],
       [ 0.00130673],
       [ 0.00130673]])

In [16]:
cycles = .5;
rate = min(max(cycles/4,0.5),2)
soc_high = min(max(cycles*100,60),100)
bat_model.bat_cycle(400,20,soc_high,rate)**(cycles/400)

array([ 0.99998681])

In [15]:
soc_high

100

In [8]:
soc_high

60

In [2]:
bat_model.bat_price_per_hour(0,16,22,300,200,100)

NameError: name 'bat_model' is not defined

In [3]:
bat_model.bat_price_per_hour(0,18,22,300,200,100)

NameError: name 'bat_model' is not defined

In [3]:
energy = 8 #kWhr
hour_start = 18 #6pm, sun goes down
hour_end = 22 #10pm, this means battery stops at 10:00pm, not 10:59
day = 343 #Dec 9th
bat_cap = 13.5 #kWhr
bat_cost = 222*bat_cap #cost scales with capacity, adjust to make numbers relavent if needed
    
cost_per_hour = bat_model.bat_price_per_hour(energy,hour_start,hour_end,day,bat_cap,bat_cost)

In [4]:
cost_per_hour

array([[ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.02831017],
       [ 0.26659312],
       [ 0.26659312],
       [ 0.26659312],
       [ 0.26659312],
       [ 0.02831017],
       [ 0.02831017]])